### ISSUE TITLE
Can't log variable that changes type

### ISSUE THREAD

**Issue by non-Jedi** [pbayer/Simulate.jl#12]
While implementing #11, I noticed that you use the `typeof` a global variable to create the array holding values of the variable. This will cause issues if the type of that variable ever changes.

In general, I'm not sure it's a great idea to support the use-case of tracking values in global scope using eval; it definitely won't perform well. It's probably better to explicitly pass around a container that has to be manually updated for all variables the user wants to track.

**Comment by pbayer** [comment]
Logging functionality removed as mentioned in #11
