### ISSUE TITLE
Include documentation example of process "getting out of sync" with clock

### ISSUE THREAD

**Issue by non-Jedi** [pbayer/Simulate.jl#14]
There's a repeated admonition to make sure a process doesn't get out of sync with the clock, but the only example given where it happens involves a process doing IO. It's implied that it's possible for a process to do so without calling a function that yields to Julia's event loop, but I'm not sure I see how.

**Comment by pbayer** [comment]
I see that the 2nd admonition: "In simulations they must take care that they keep synchronized with the clock" under "Delay, wait, take and put" is not clear. I removed it. And I changed the sequence of the first such warning. see commit [9877f42](https://github.com/pbayer/Simulate.jl/commit/9877f421a0b9cafc452a3cb9b0014bc6fd8ac96b) 

Does this resolve the issue?

**Comment by pbayer** [comment]
further clarification with commit [ff5119](https://github.com/pbayer/Simulate.jl/commit/ff5119e1d1f37536e14dacd0a950832edfa49562)

**Comment by pbayer** [comment]
I close this now since I think it is solved (got no further objections).
Please reopen if this is still an issue.

**Comment by non-Jedi** [comment]
This is much more clear to me now. Thanks. :)
